// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIdwh0lNEpF4EtI0VXhjSxBz56iEL6Pk4',
    appId: '1:135399620306:web:5cb551e19a06509822f70b',
    messagingSenderId: '135399620306',
    projectId: 'demomodul666',
    authDomain: 'demomodul666.firebaseapp.com',
    storageBucket: 'demomodul666.firebasestorage.app',
    measurementId: 'G-ZFWN0SRWDN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH3VkVaKYbVeplvDYz6o9V2BJwlgcNgj4',
    appId: '1:135399620306:android:c46637e7c29b515922f70b',
    messagingSenderId: '135399620306',
    projectId: 'demomodul666',
    storageBucket: 'demomodul666.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByn1t8Nm8mtKpiHmRNCmLBqERXn1h4NU0',
    appId: '1:135399620306:ios:a539823c9b36c0b122f70b',
    messagingSenderId: '135399620306',
    projectId: 'demomodul666',
    storageBucket: 'demomodul666.firebasestorage.app',
    iosBundleId: 'com.example.overloadedclean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIdwh0lNEpF4EtI0VXhjSxBz56iEL6Pk4',
    appId: '1:135399620306:web:548ae848262d827c22f70b',
    messagingSenderId: '135399620306',
    projectId: 'demomodul666',
    authDomain: 'demomodul666.firebaseapp.com',
    storageBucket: 'demomodul666.firebasestorage.app',
    measurementId: 'G-3YXLCMPZZL',
  );

}